In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


# Creating a tuple

In [4]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# Dimensional Arrays

### 0-D

In [5]:
arr = np.array(36)
print(arr)

36


### 1-D

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### 2-D

In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 3-D

In [12]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [14]:
print(arr.ndim)

3


In [16]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [19]:
print(a.ndim)

2


In [21]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# Datatypes

In [22]:
dt = np.dtype(np.int32) 
print(dt)

int32


In [23]:
dt = np.dtype('i4')
print(dt) 

int32


In [24]:
dt = np.dtype('>i4') 
print(dt)

>i4


In [25]:
dt = np.dtype([('age',np.int8)]) 
print(dt) 

[('age', 'i1')]


In [26]:
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [27]:
print(a.shape)

(3,)


# Item Size

In [28]:
print(a.itemsize)

1


In [29]:
print(arr.itemsize)

4


In [31]:
x = np.ones(5) 
print(x)

[1. 1. 1. 1. 1.]


# Indexing and Slicing

In [32]:
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])

[2 4 6]


In [33]:
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [34]:
a = np.arange(10) 
b = a[5] 
print(b)

5


### Advanced Slicing

In [35]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [36]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print('Our array is:') 
print(x)
print('\n')  
# Now we will print the items greater than 5 
print('The items greater than 5 are:') 
print(x[x > 5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]
