In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
data = pd.read_csv('C:/Users/Dell/Desktop/data-set/car_evaluation.csv')

In [5]:
data.head()

buying  maint doors persons lug_boots safety  class
0  vhigh  vhigh     2       2     small    low  unacc
1  vhigh  vhigh     2       2     small    med  unacc
2  vhigh  vhigh     2       2     small   high  unacc
3  vhigh  vhigh     2       2       med    low  unacc
4  vhigh  vhigh     2       2       med    med  unacc

In [54]:
X = data[['buying', 'maint', 'safety']].values
y = data['class']

In [55]:
X

array([['vhigh', 'vhigh', 'low'],
       ['vhigh', 'vhigh', 'med'],
       ['vhigh', 'vhigh', 'high'],
       ...,
       ['low', 'low', 'low'],
       ['low', 'low', 'med'],
       ['low', 'low', 'high']], dtype=object)

In [56]:
y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...  
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: class, Length: 1728, dtype: object

# Converting data into integers

In [57]:
Le = LabelEncoder()

In [58]:
for i in range(len(X[0])):
    X[:, i] = Le.fit_transform(X[:, i])

In [59]:
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


# Converting y

In [60]:
label_mapping = {'unacc': 0, 'acc': 1, 'good': 2, 'vgood': 3}

In [72]:
y = pd.Categorical(data['class']).codes
y

array([2, 2, 2, ..., 2, 1, 3], dtype=int8)

# Creating the Model

In [73]:
knn = neighbors.KNeighborsClassifier(n_neighbors = 25, weights = 'uniform')

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [75]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=25)

In [76]:
prediction = knn.predict(X_test)

In [77]:
print(prediction)

[2 3 2 2 2 3 2 0 2 0 1 3 2 3 2 2 2 2 2 2 0 2 0 0 2 2 2 2 0 1 2 2 1 1 0 2 0
 2 2 2 0 2 2 2 2 2 0 2 0 0 0 2 2 0 2 2 0 2 2 0 2 3 2 2 2 2 2 2 2 2 2 2 1 2
 2 0 0 2 0 2 2 0 2 2 2 3 2 0 2 2 0 2 1 0 2 2 2 0 2 0 0 2 2 2 0 2 2 2 0 2 0
 2 0 2 2 2 2 2 2 2 0 2 2 2 1 3 2 2 2 3 1 2 0 2 2 2 2 0 2 2 2 2 0 2 0 0 0 2
 0 2 0 2 2 2 2 2 0 2 2 0 2 2 2 0 2 2 2 2 0 2 2 0 2 0 2 2 2 2 2 2 2 2 2 0 2
 2 2 3 0 2 2 2 2 0 3 2 2 3 2 3 2 0 2 2 2 2 2 2 3 2 2 2 2 2 0 3 2 0 2 2 2 0
 2 1 2 2 2 0 2 2 2 2 2 0 0 3 2 0 2 2 2 2 2 2 3 2 0 2 2 2 2 2 0 0 2 3 2 1 2
 2 2 2 2 0 2 3 2 2 2 2 2 2 3 1 2 2 2 2 2 2 3 2 2 2 2 2 0 2 2 3 2 0 2 2 0 2
 1 0 2 1 2 2 0 2 2 0 2 2 2 0 2 2 0 2 2 2 2 2 2 1 2 0 2 2 0 2 2 2 2 2 3 0 2
 2 2 2 0 2 2 0 2 2 2 2 2 2]


In [78]:
accuracy = metrics.accuracy_score(y_test, prediction)
print("accuracy", accuracy)

accuracy 0.7456647398843931


In [79]:
print("Actual Value: ", y[20])
print("Predicted Value: ", knn.predict(X)[20])

Actual Value:  2
Predicted Value:  2
